services:
    postgres:
            container_name: another-elysia-postgres
            image: postgres:latest
            restart: unless-stopped
            environment:
                - POSTGRES_USER=another-elysia
                - POSTGRES_PASSWORD=Please-change-password
                - POSTGRES_DB=another-elysia
            ports:
                - 5432:5432
            volumes:
                - postgres_data:/var/lib/postgresql/data
    
volumes:
    postgres_data:
    
networks:
    default: {}